Describes
JamesMorales04/protractor-workshop pull request #14
Opened 2021-06-28 20:37 UTC by JamesMorales04

Módulo 15

2021-06-28 20:50 UTC, aperdomob requested changes

2021-06-28 20:50 UTC, aperdomob commented on test/buy-tshirt.spec.ts
> +            await bankPaymentPage.goToOrderSummaryMenu();
add into beforeAll

2021-06-29 15:54 UTC, holgiosalos commented on test/buy-tshirt.spec.ts
> +    const summaryStepPage: SummaryStepPage = new SummaryStepPage();
you can move the initialization of page objects within the `beforeAll` of te corresponding describe

2021-06-29 16:11 UTC, holgiosalos approved these changes

2021-06-29 17:05 UTC, merged